### ISSUE TITLE
PLZ teach me how to run the simulation

### ISSUE THREAD

**Issue by imhere111** [KumarRobotics/spomp-system#5]
Thank you very much ,plz! I have already downloaded and compiled the Docker environment and code. What is the next step to run the ROS simulation? If the launch files under semantics_manager are for starting the drone and vehicle, where can I find the corresponding RViz map simulation files? Please help me with this. Thank you!

**Comment by iandouglas96** [comment]
At this time, we are (sadly) unable to release the simulator itself.  The code that is here is for running on robots only, though you could provide your own simulator if you would like.
